config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  resources :marks
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 before_action :authenticate_student!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
      @mark = Mark.find(current_student.id)
	end
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  before_action :set_mark, only: [:show, :edit, :update, :destroy]

  # GET /marks
  # GET /marks.json
  def index
    @marks = Mark.all
  end

  # GET /marks/1
  # GET /marks/1.json
  def show
  end

  # GET /marks/new
  def new
    @mark = Mark.new
  end

  # GET /marks/1/edit
  def edit
  end

  # POST /marks
  # POST /marks.json
  def create
    @mark = Mark.new(mark_params)

    respond_to do |format|
      if @mark.save
        format.html { redirect_to @mark, notice: 'Mark was successfully created.' }
        format.json { render :show, status: :created, location: @mark }
      else
        format.html { render :new }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marks/1
  # PATCH/PUT /marks/1.json
  def update
    respond_to do |format|
      if @mark.update(mark_params)
        format.html { redirect_to @mark, notice: 'Mark was successfully updated.' }
        format.json { render :show, status: :ok, location: @mark }
      else
        format.html { render :edit }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marks/1
  # DELETE /marks/1.json
  def destroy
    @mark.destroy
    respond_to do |format|
      format.html { redirect_to marks_url, notice: 'Mark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mark
      @mark = Mark.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mark_params
      params.require(:mark).permit(:name, :mark1, :mark2, :mark3, :total, :grade, :student_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/views/home/index.html.erb
<h2>Student Name : <%= @mark.name%><br /><br />
Mark1 <%= @mark.mark1 %><br /><br />
Mark2 <%= @mark.mark2 %><br /><br />
Mark3 <%= @mark.mark3 %><br /><br />

Total <%= @mark.total %><br /><br />

Grade <%= @mark.grade %> </h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      


  <div class="header">
    
    <div class="title">
      <h1>Student App</h1>
    </div>

    <div class="navigation">
      <a href="index.html">Vestibulum</a>
      <a href="index.html">Suspendisse</a>
      <a href="index.html">Elemen</a>
      <a href="index.html">Maecenas</a>
      <a href="index.html">Sodales</a>
      <div class="clearer"><span></span></div>
    </div>

  </div>

  <div class="main">
    <p class="navbar-text float-right">
<% if student_signed_in? %>
  Logged in as <strong><%= current_student.email %></strong>.
  <%= link_to 'Edit profile', edit_student_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_student_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_student_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_student_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
    <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
  
    <div class="content">

      <%= yield %>
    </div>

    <div class="sidenav">

      <h1>Search</h1>
      <form action="index.html">
      <div>
        <input type="text" name="search" class="styled" /> <input type="submit" value="submit" class="button" />
      </div>
      </form>

      <h1>Something</h1>
      <ul>
        <li><a href="index.html">pellentesque</a></li>
        <li><a href="index.html">sociis natoque</a></li>
        <li><a href="index.html">convallis</a></li>
      </ul>

      <h1>Another thing</h1>
      <ul>
        <li><a href="index.html">consequat molestie</a></li>
        <li><a href="index.html">sem justo</a></li>
        <li><a href="index.html">semper</a></li>
      </ul>

      <h1>Third and last</h1>
      <ul>
        <li><a href="index.html">sociis natoque</a></li>
        <li><a href="index.html">magna sed purus</a></li>
        <li><a href="index.html">tincidunt</a></li>
      </ul>

    </div>
  
    <div class="clearer"><span></span></div>

  </div>

</div>

<div class="footer">&copy; 2020
</div>

  </body>
</html>

app/views/marks/_form.html.erb
<%= form_with(model: mark, local: true) do |form| %>
  <% if mark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mark.errors.count, "error") %> prohibited this mark from being saved:</h2>

      <ul>
        <% mark.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :mark1 %>
    <%= form.number_field :mark1 %>
  </div>

  <div class="field">
    <%= form.label :mark2 %>
    <%= form.number_field :mark2 %>
  </div>

  <div class="field">
    <%= form.label :mark3 %>
    <%= form.number_field :mark3 %>
  </div>

  <div class="field">
    <%= form.label :total %>
    <%= form.number_field :total %>
  </div>

  <div class="field">
    <%= form.label :grade %>
    <%= form.text_field :grade %>
  </div>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.text_field :student_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/marks/edit.html.erb
<h1>Editing Mark</h1>

<%= render 'form', mark: @mark %>

<%= link_to 'Show', @mark %> |
<%= link_to 'Back', marks_path %>

app/views/marks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Marks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mark1</th>
      <th>Mark2</th>
      <th>Mark3</th>
      <th>Total</th>
      <th>Grade</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @marks.each do |mark| %>
      <tr>
        <td><%= mark.name %></td>
        <td><%= mark.mark1 %></td>
        <td><%= mark.mark2 %></td>
        <td><%= mark.mark3 %></td>
        <td><%= mark.total %></td>
        <td><%= mark.grade %></td>
        <td><%= mark.student_id %></td>
        <td><%= link_to 'Show', mark %></td>
        <td><%= link_to 'Edit', edit_mark_path(mark) %></td>
        <td><%= link_to 'Destroy', mark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mark', new_mark_path %>

app/views/marks/new.html.erb
<h1>New Mark</h1>

<%= render 'form', mark: @mark %>

<%= link_to 'Back', marks_path %>

app/views/marks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mark.name %>
</p>

<p>
  <strong>Mark1:</strong>
  <%= @mark.mark1 %>
</p>

<p>
  <strong>Mark2:</strong>
  <%= @mark.mark2 %>
</p>

<p>
  <strong>Mark3:</strong>
  <%= @mark.mark3 %>
</p>

<p>
  <strong>Total:</strong>
  <%= @mark.total %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @mark.grade %>
</p>

<p>
  <strong>Student:</strong>
  <%= @mark.student_id %>
</p>

<%= link_to 'Edit', edit_mark_path(@mark) %> |
<%= link_to 'Back', marks_path %>